# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Intentionally not adding automatic NPM updates because I do
  # not trust the plugin's tests to catch issues caused by updates.
  # TODO or enable, but avoid merging without first doing a local interactive test?
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
    - dependency-name: org.codehaus.groovy:groovy
    # Must match transitive version from org.jenkins-ci.plugins:subversion:
    - dependency-name: org.tmatesoft.svnkit:svnkit-cli
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
